accounts/urls.py
from django.urls import re_path

from .views import (
    login_view,
    register_view,
    logout_view
)

urlpatterns = [
    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
]

app_name = 'accounts'

scopus_abstract_extraction/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from core.views import home, get_abstract, get_csv

urlpatterns = [
                  # admin

                  path('admin/', admin.site.urls),
                  # Accounts
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  # core
                  path('', home, name='home'),
                  # transactions
                  path('', include('transactions.urls', namespace='transactions')),
                  re_path(r'^category/(?P<category_id>\d+)$', get_abstract, name="get_abstract"),
                  re_path(r'^category/get/(?P<category_id>\d+)$', get_csv, name="get_csv"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path

from .views import category_view, UploadDocView, upload, doc_list, upload_doc, delete_doc, DocListView

urlpatterns = [
    path('addcat/', category_view, name='create_category'),
    path('upload/', upload, name='upload'),
    path('docs/', doc_list, name='doc_list'),
    path('docs/upload/', upload_doc, name='upload_doc'),
    path('docs/<int:pk>/', delete_doc, name='delete_doc'),
    path('class/docs/', DocListView.as_view(), name='class_doc_list'),
    path('class/docs/upload/', UploadDocView.as_view(), name='class_upload_doc'),
]

app_name = 'transactions'

core/views.py
import csv
from datetime import datetime
import logging
import requests
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from transactions.models import Category, Dataset, Document

logger = logging.getLogger(__name__)


def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})
    else:
        user = request.user
        category = Category.objects.filter(user=request.user)
        category_obj = Dataset.objects.filter(category__user=request.user)
        context = {
            "user": user,
            "category": category,
            "category_obj": category_obj,
        }

        return render(request, "core/transactions.html", context)


API_KEY = 'e947957924671f20b87c8437ae30ba05'


def run_scopus_search(query):
    return requests.get(
        'https://api.elsevier.com/content/search/scopus?&query=%s&field=dc:identifier' % query,
        headers={'Accept': 'application/json', 'X-ELS-APIKey': API_KEY}).json()


def get_scopus_ids(res):
    return [[str(r['dc:identifier'])] for r in res['search-results']['entry']]


def get_scopus_info(id):
    url = ('https://api.elsevier.com/content/abstract/scopus_id/' + id + '?field=dc:description')
    return requests.get(url, headers={'Accept': 'application/json', 'X-ELS-APIKey': API_KEY}).json()


@login_required()
def get_abstract(request, category_id=None):
    if Document.objects.filter(category=category_id):
        file_obj = Document.objects.get(category=category_id).docfile
    else:
        return redirect('transactions:upload_doc')
    with file_obj as file:
        for line in file:
            line = str(line)[2:-3]
            results = run_scopus_search(line)
            try:
                scopus_ids = get_scopus_ids(results)[0]
                try:
                    results_info = get_scopus_info(scopus_ids[0])
                    try:
                        abstract = results_info['abstracts-retrieval-response']['coredata']['dc:description']
                        if abstract == 'None':
                            logger.error(scopus_ids[0], " None", end='')
                            continue
                        Dataset(scopus_id=scopus_ids[0], abstract=abstract, timestamp=datetime.now(),
                                category_id=category_id).save()
                    except Exception as e:
                        logger.error(e, "\nAbstract not available")
                        continue
                except Exception as e:
                    logger.error(e, '\n', scopus_ids[0], "Result error")
                    continue
            except Exception as e:
                logger.error(e, 'Error get_scopus_ids')
    if not request.user.is_authenticated:
        return render(request, "core/home.html", {})
    else:
        context = {
            "text": line,
        }
        return render(request, "core/script_panel.html", context)


@login_required()
def get_csv(request, category_id=None):
    response = HttpResponse(content_type='text/csv')

    writer = csv.writer(response)
    writer.writerow(['Scopus ID', 'Abstract', 'Creation time'])

    for line in Dataset.objects.all().filter(category_id=category_id).values_list('scopus_id', 'abstract', 'timestamp'):
        writer.writerow(line)

    response['Content-Disposition'] = 'attachment; filename="abstracts.csv"'

    return response

templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} About | {{ block.super }}{% endblock title %}

{% block content %}

    <h1>About</h1>
    <hr>
    <form method="post" action="{% url "run_script" %}">
        {% csrf_token %}
        <button type="submit" name="run_script">Run script</button>
    </form>
{% endblock content %}

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %} Scopus abstract extraction {% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
{% include "core/navbar.html" %}

<div class="container" style="padding-top: 60px;">
    {% block content %}

    {% endblock content %}
</div>
{% include "core/footer.html" %}

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/core/footer.html
<footer class="footer navbar-fixed">
    <hr>
    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            <div class="col-md-6">
                <h4 class="title"><b>Scopus abstract extractor</b></h4>

            </div>
            <!--/.First column-->
            <!--Second column-->
            <div class="col-md-6">
                <h5 class="title"><b>Links</b></h5>

                <a href="{% url 'home' %}">Home </a>|
                <a href="{% url 'transactions:doc_list' %}">Files</a> |&nbsp;


            </div>
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            2020 <a href="https://github.com/ikochura/scopus_abstract_extraction">Github</a>
        </div>
    </div>
    <!--/.Copyright-->
</footer>
<br>

templates/core/home.html
{% extends 'core/base.html' %}

<body>
{% block title %} {{ block.super }}{% endblock title %}

{% block content %}
    <div class="container" style="padding-top: 50px;">
        <div class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">Scopus abstract extraction</h1>
                <hr>
                <p class="lead text-muted">This site is intended for obtaining a set of data for further training of
                    neural networks with natural language processing methods.</p>
                <p>
                    <a class="btn btn-primary btn-md" href="{% url 'accounts:login' %}" role="button">Sign in</a>
                    <a class="btn btn-success btn-md" href="{% url 'accounts:register' %}" role="button">Sign up</a>
                </p>
            </div>
        </div>
    </div>

{% endblock content %}
</body>

templates/core/messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}

templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Scopus abstract extractor</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transactions:create_category' %}">Create category</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transactions:doc_list' %}">Files</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}" class="btn btn-danger btn-sm" type="button">Logout</a>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-success btn-sm" type="button">Sign in</a> |
                <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-sm" type="button">Sign up</a>
            {% endif %}
        </form>
    </div>
</nav>

templates/core/script_panel.html
{% extends 'core/base.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>f</title>
</head>
<body>
{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
    {% include "core/messages.html" %}

    <div class="page-header">
        <h1 class="text-center"><b>Scopus abstract extraction</b></h1>
    </div>

    <div class="row">

        <div class="col-xs-12 col-md-8 text-left">
            <h4><b>Account Name: </b>{{ user.full_name }}</h4>
            <h4><b>Email Address: </b>{{ user.email }}</h4>
        </div>
        <div class="col-xs-6 col-md-4 text-left">
            <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
        </div>

    </div>

    <hr>

    <div class="page-header">
        <h2 class="text-center"><b>Transaction Details</b></h2>
    </div>
    <div id="modal">
        {{ text }}
    </div>
{% endblock content %}
</body>
</html>

templates/core/transactions.html
{% extends 'core/base.html' %}
<head>
    <link rel="stylesheet" href="/static/css/main.css">
    <title>f</title>
</head>
{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
    {% include "core/messages.html" %}

    <div class="page-header">
        <h1 class="text-center"><b>Details</b></h1>
    </div>

    <div class="row">

        <div class="col-xs-12 col-md-8 text-left">
            <h4><b>Account Name: </b>{{ user.full_name }}</h4>
            <h4><b>Email Address: </b>{{ user.email }}</h4>
        </div>
        <div class="col-xs-6 col-md-4 text-left">
            <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
        </div>

    </div>

    <hr>

    <div class="page-header">
        <h2 class="text-center"><b>Category list</b></h2>
    </div>


    <table class="table table-hover table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Date / Time</th>
            <th>Get abstracts</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% if category %}
                {% for obj in category %}
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ obj.name_group_dataset }}</td>
                    <td>{{ obj.timestamp }}</td>
                    <td><a class="btn btn-danger" href="{% url 'get_abstract' obj.id %}">Start</a>
                        <a class="btn btn-success" href="{% url 'get_csv' obj.id %}">CSV</a>
                    </td>
                    </tr>
                {% endfor %}
            {% else %}
                <td><p>No objects are available right now.</p></td>
            {% endif %}
        <tr>
            <th class="text-right" scope="row" colspan="3">Total</th>

            <td>{{ category_obj.count }}</td>
        </tr>

        </tbody>
    </table>
{% endblock content %}